OnlineShop/Controllers/HomeController.cs
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        ShoppingStoreEntities StoreDB = new ShoppingStoreEntities();
        private List<Item>GetTopSellingItems(int count)
        {
            return StoreDB.Items.OrderByDescending(i => i.OrderDetails.Count())
              .Take(count)
               .ToList();
        }
        public ActionResult Index()
        {
            var items = GetTopSellingItems(10);
            return View(items);
        }
    

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OnlineShop/Controllers/ShoppingCartController.cs
using OnlineShop.Models;
using OnlineShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    /*shoppingcartcontroller ka tre qellime*/
    /*1.shton itemsat ne shporte*/
    /*2.heq itemsat nga shporta jone*/
    /*3.shfaqe itemsat ne shporten tone*/
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart

            ShoppingStoreEntities storeDB = new ShoppingStoreEntities();

            public ActionResult Index()
            {
                var cart = ShoppingCart.GetCart(this.HttpContext);


                var viewModel = new ShoppingCartViewModel
                {
                    CartItems = cart.GetCartItems(),
                    CartTotal = cart.GetTotal()
                };

                return View(viewModel);
            }
        /*merr id e itemsave si parameter*//*lorena*/
            public ActionResult AddToCart(int id)
            {
            /* i shton ne databaze*/
                var addedItem = storeDB.Items
                    .Single(item => item.ItemId == id);


                var cart = ShoppingCart.GetCart(this.HttpContext);

                cart.AddToCart(addedItem);

            /*pastaj i ridjeton per te pare itemsa tee tjere*/
                return RedirectToAction("Index");
            }
        /*motoda e hqejes se itemsit,merr parameter id item*/
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {

            var cart = ShoppingCart.GetCart(this.HttpContext);

            /*merr emrin e itemsit nga databaza*/
            string itemName = storeDB.Carts.Single(item => item.RecordId == id).Item.Title;

            /*e heq nga databaza*/
            int itemCount = cart.RemoveFromCart(id);
            /*pastaj shfaq kete mesazh te useri per te konfimuar me userin heqjen e itemsit nga shporta*/

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

    }
}

OnlineShop/Controllers/StoreController.cs
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class StoreController : Controller
    {
        ShoppingStoreEntities storeDB = new ShoppingStoreEntities();
        // GET: Store
        public ActionResult Index()
        {
            var categories = storeDB.Categories.ToList();
    
            return View(categories);
        }


        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var categories = storeDB.Categories.ToList();
            return PartialView(categories);

        }
        public ActionResult Browse(string category)
        {
            var categoryModel = storeDB.Categories.Include("Items")
                .Single(c => c.Name == category);

            return View(categoryModel);
        }
        public ActionResult Details (int id)
        {
            var Item = storeDB.Items.Find(id);
            return View(Item);
        }
    }
}

OnlineShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineShop/Views/Home/Index.cshtml
<br /><br /><br />
<div id="carouselBlk">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item active">
                <div class="container">
                    <a href="/Account/Register">
                        <img style="width:55%" src="~/Content/images/biznesattire.jpg"  alt="" />
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh.</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="/Account/Register">
                        <img style="width:55%"
                         src="~/Content/images/biznesattire2.jpg" /> 
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh.</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="/Account/Register">
                        
                        <img   style="width:55%" src="~/Content/images/casualwear3.jpg" alt="" />
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh</p>
                    </div>

                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="/Account/Register">
                     
                        <img   style="width:55%" src="~/Content/images/casualwear3.jpg"  alt="" />
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh</p>
                    </div>

                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="/Account/Register">
                        <img  style="width:55%"  src="~/Content/images/formalwear.jpg"  alt="" />
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="/Account/Register">
                        <img  style="width:55%"  src="~/Content/images/sportswear3.jpg"  alt="" />
                    </a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>For a bit of drama and tons of coziness, the oversized turtleneck is a cold-weather staple whether you prefer a swingy, hip-grazing fit or an ultra-roomy design nearly hitting mid-thigh.</p>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>
<li>@{Html.RenderAction("CategoryMenu", "Store");}</li>

<h3>Top 10 Items In Our Store</h3>
<ul id="item-list">

    @foreach (var item in Model)
    {

        <li>
            <a href="@Url.Action("Details","Store",new { id = item.ItemId })">
                <img alt="@item.Title" src="@item.ItemArtUrl" />
                <br />

                <span>@item.Title</span>
            </a>

            @String.Format("{0:F}", item.Price)$
            <p class="button1">

                @Html.ActionLink("Add to cart", "AddToCart",
        "ShoppingCart", new { id = item.ItemId }, new { @class = "btn btn-danger" })
            </p>
        </li>



    }


</ul>